### ISSUE TITLE
Performance regression 

### ISSUE THREAD

**Issue by jsg2021** [webpack-contrib/eslint-webpack-plugin#83]
By moving the finishModule hook we no longer spread the linting work out... one lump (in my case 5620 files) gets sent to the linter in one go. The thread pool (if threaded) does not fill up... only one worker gets all the jobs.

_Originally posted by @jsg2021 in https://github.com/webpack-contrib/eslint-webpack-plugin/issues/73#issuecomment-777122580_

**Comment by ricardogobbosouza** [comment]
Resolved on [v2.5.1](https://github.com/webpack-contrib/eslint-webpack-plugin/releases/tag/v2.5.1)

**Comment by jsg2021** [comment]
I'm afraid this doesn't solve the performance regression. By dispatching a single `lint(files);` at the end we negate the thread pool's parallelization. The call to `lint(files)` is dispatched to a single worker... lint needs to be called as modules are found so that it can be run in parallel with the build.

**Comment by jsg2021** [comment]
Maybe we can lump all the files at the end if we aren't threaded?
